name: Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kcov
        run: |
          sudo apt-get update
          sudo apt-get install -y kcov

      - name: Make Scripts Executable
        run: |
          chmod +x ./random-listening.sh
          chmod +x ./test.sh

      - name: Run Tests with kcov
        run: |
          mkdir -p coverage
          kcov --include-path=$(pwd) coverage ./test.sh

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
