name: Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies for kcov
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libcurl4-openssl-dev libssl-dev zlib1g-dev libdw-dev libiberty-dev binutils-dev

      - name: Build and Install kcov v43
        run: |
          git clone https://github.com/SimonKagstrom/kcov.git
          cd kcov
          git checkout v43
          mkdir build
          cd build
          cmake ..
          make
          sudo make install
          cd ../..
          rm -rf kcov

      - name: Make Scripts Executable
        run: |
          chmod +x ./random-listening.sh && chmod +x ./test.sh

      - name: Run Tests with kcov
        run: |
          mkdir -p coverage && kcov --cobertura-only coverage ./test.sh

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
